package Final.Lab2;

public class Example4 {
		   public static void main(String args[]){
			   
		    try{
		    	
		       int d = 0;
		       int n =30;
		       int fraction = d/n;
		    }
		    
		  catch(ArithmeticException e){
			  
		    System.out.println("In the catch block = "+e);
		  }
		    
		  finally{
			  
			System.out.println("Inside the final block");
		  }
		}
		}
